app:
  build: "./app"
  container_name: "app"
  ports:
  - "5000:80"
  volumes:
    - ./app:/app
    - ./log:/var/log

  environment:
    - FILE_NAME=./data/test_data.csv
    - CHUNK_SIZE=10
    - NUM_MAX_DOCS=50
