app:
  build: "./app"
  container_name: "app"
  ports:
  - "5000:80"
  volumes:
    - ./app:/app
    - ./log/nginx:/var/log/nginx
  links:
  - "redis"
redis:
  image: "redis:3"
  container_name: "redis"
  volumes:
    - "$PWD/redis:/data"
  command: redis-server --appendonly yes
