swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: localhost:5000
basePath: /
schemes:
  - http
paths:
  /docs/{documentId}:
    get:
      summary: Returns similar documents by ID.
      parameters:
        - in: path
          name: documentId
          required: true
          type: integer
          minimum: 1
          description: Parameter description in Markdown.
      responses:
        200:
          description: OK